---
- name: Populate service facts
  service_facts:

- name: Stop zookeeper service
  systemd:
    name: '{{ zk_service_name }}'
    state: stopped
    enabled: False
  become: True
  when: zk_service_name + '.service' in ansible_facts.services

- name: Choose platform based task
  include_tasks: '{{ zk_task_uninstall }}'
  with_first_found:
    - '{{ zk_uninstall_type }}/{{ ansible_system }}.yml'
    - '{{ zk_uninstall_type }}/{{ ansible_os_family }}.yml'
    - not-supported.yml
  loop_control:
    loop_var: zk_task_uninstall

- name: Reload deamon
  systemd:
    daemon_reload: True
  become: True
